name = "nextjs-blog"
compatibility_date = "2025-01-27"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

[vars]
NODE_ENV = "production"

[assets]
directory = ".next/static"
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"

# Custom headers for better caching
[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]] 
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/api/*"
[headers.values]
Cache-Control = "public, max-age=300"

# SEO and security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"