name = "ai-lodi-blog"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
name = "ai-lodi-blog"

[env.preview]
name = "ai-lodi-blog-preview"